version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CRM
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"